# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rev.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ekran(object):
    def setupUi(self, ekran):
        ekran.setObjectName("ekran")
        ekran.resize(720, 426)
        self.centralwidget = QtWidgets.QWidget(ekran)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_hesapla = QtWidgets.QPushButton(self.centralwidget)
        self.btn_hesapla.setGeometry(QtCore.QRect(210, 140, 101, 31))
        self.btn_hesapla.setObjectName("btn_hesapla")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 121, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 40, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.label_4.setObjectName("label_4")
        self.txt_kesme = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_kesme.setGeometry(QtCore.QRect(50, 113, 51, 16))
        self.txt_kesme.setObjectName("txt_kesme")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 113, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 123, 131, 20))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 138, 31, 21))
        self.label_6.setObjectName("label_6")
        self.txt_cap = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_cap.setGeometry(QtCore.QRect(80, 140, 51, 16))
        self.txt_cap.setObjectName("txt_cap")
        self.txt_devir = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_devir.setGeometry(QtCore.QRect(230, 109, 51, 21))
        self.txt_devir.setObjectName("txt_devir")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 180, 321, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(250, 50, 61, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(220, 60, 111, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(260, 70, 31, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(200, 110, 121, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(360, 10, 311, 181))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(100, 10, 141, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(340, -10, 16, 481))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(0, 210, 741, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(120, 230, 121, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(30, 260, 81, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(210, 320, 121, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(10, 300, 47, 21))
        self.label_19.setObjectName("label_19")
        self.btn_feed = QtWidgets.QPushButton(self.centralwidget)
        self.btn_feed.setGeometry(QtCore.QRect(210, 350, 121, 31))
        self.btn_feed.setObjectName("btn_feed")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(360, 230, 351, 141))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(80, 300, 47, 21))
        self.label_21.setObjectName("label_21")
        self.txt_rev = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_rev.setGeometry(QtCore.QRect(100, 300, 31, 20))
        self.txt_rev.setText("")
        self.txt_rev.setObjectName("txt_rev")
        self.btn_kopy = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kopy.setGeometry(QtCore.QRect(90, 330, 51, 23))
        self.btn_kopy.setObjectName("btn_kopy")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(140, 300, 47, 21))
        self.label_22.setObjectName("label_22")
        self.txt_feed_teeth = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_feed_teeth.setGeometry(QtCore.QRect(160, 300, 31, 20))
        self.txt_feed_teeth.setText("")
        self.txt_feed_teeth.setObjectName("txt_feed_teeth")
        self.txt_feed = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_feed.setGeometry(QtCore.QRect(230, 320, 51, 21))
        self.txt_feed.setObjectName("txt_feed")
        self.txt_teeth = QtWidgets.QSpinBox(self.centralwidget)
        self.txt_teeth.setGeometry(QtCore.QRect(30, 300, 42, 22))
        self.txt_teeth.setMinimum(1)
        self.txt_teeth.setMaximum(20)
        self.txt_teeth.setObjectName("txt_teeth")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(580, 360, 131, 31))
        self.label_23.setObjectName("label_23")
        ekran.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ekran)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        ekran.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ekran)
        self.statusbar.setObjectName("statusbar")
        ekran.setStatusBar(self.statusbar)

        self.retranslateUi(ekran)
        QtCore.QMetaObject.connectSlotsByName(ekran)

    def retranslateUi(self, ekran):
        _translate = QtCore.QCoreApplication.translate
        ekran.setWindowTitle(_translate("ekran", "Devir Hesabı"))
        self.btn_hesapla.setText(_translate("ekran", "Deviri Hesapla"))
        self.label.setText(_translate("ekran", "  N = -------------------"))
        self.label_3.setText(_translate("ekran", "Vc  * 1000"))
        self.label_4.setText(_translate("ekran", "π * D"))
        self.label_5.setText(_translate("ekran", "* 1000"))
        self.label_2.setText(_translate("ekran", "N = --------------------------               "))
        self.label_6.setText(_translate("ekran", "π   *"))
        self.label_7.setText(_translate("ekran", "Sonuç:"))
        self.label_8.setText(_translate("ekran", "π * D * N"))
        self.label_9.setText(_translate("ekran", " Vc = -------------------"))
        self.label_10.setText(_translate("ekran", "1000"))
        self.label_11.setText(_translate("ekran", "N=                           d/dk"))
        self.label_12.setText(_translate("ekran", "    #NOTLAR\n"
"Freze için devir hesaplanacaksa D kullanılan takımın çapını, \n"
"N ise takımın devrini ifade eder. \n"
"\n"
"Torna için devir hesaplanacaksa D iş parçasının çapını, \n"
"N ise iş parçası devrini ifade eder.\n"
"\n"
"Vc:m/dak\n"
"Katologdan alınan kesme hızını ifade eder.(Helisel)\n"
"π:3,1415\n"
"D:mm\n"
"N:d/dak\n"
""))
        self.label_13.setText(_translate("ekran", "TORNA-FREZE DEVİR HESABI"))
        self.label_14.setText(_translate("ekran", "|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|"))
        self.label_15.setText(_translate("ekran", "-----------------------------------------------------------------------------------       ---------------------------------------------------------------------------------------------------"))
        self.label_16.setText(_translate("ekran", "TABLA İLERLEMESİ"))
        self.label_17.setText(_translate("ekran", "F =  z * N * fz"))
        self.label_18.setText(_translate("ekran", "F =                   mm/dak"))
        self.label_19.setText(_translate("ekran", "z = "))
        self.btn_feed.setText(_translate("ekran", "İlerleme Hesapla"))
        self.label_20.setText(_translate("ekran", "    #NOTLAR\n"
"#\"Kullan\" butonuna basılırsa hesaplanan devir değeri kullanılır.\n"
"F Tabla ilerlemesini ifade eder.\n"
" n kesici takım için diş sayısını ifade eder.\n"
" N bir önceki denklemde hesaplanan devri ifade eder.\n"
" fz seçilen kesici takıma bağlı olarak katologtan alınandiş başına \n"
"veya devir başına ilerlemeyi ifade eder.\n"
"F:mm/dak\n"
"z:Freze diş sayısı\n"
"fz:katologdan alınan diş başına ilerleme\n"
"N:d/dk\n"
""))
        self.label_21.setText(_translate("ekran", "N = "))
        self.btn_kopy.setText(_translate("ekran", "Kullan"))
        self.label_22.setText(_translate("ekran", "fz = "))
        self.label_23.setText(_translate("ekran", "created by bayramkuru"))
